[package]
name = "dorp"
version = "0.1.0"
authors = ["Kiley Owen <owenk@wit.edu>"]

[lib]
name = "dorp"
path = "src/lib.rs"

[[bin]]
name = "dorp_bin"
path = "src/bin/main.rs"

[dependencies]
glium = "0.13.5"
time = "0.1.34"
image = "0.6.1"
scoped_threadpool = "0.1.7"
